# Generated by Django 3.1.3 on 2020-11-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='uphone',
            field=models.CharField(default=None, max_length=11),
        ),
    ]
